version: '2'
services:
 mysql:
  build: ./mysql
  environment: 
   MYSQL_DATABASE: appform
   MYSQL_ROOT_PASSWORD: admin
  volumes:
   - ./dbData:/var/lib/mysql
   - /etc/localtime:/etc/localtime:ro

 apache:
  build: ./apache
  volumes:
   - ./www:/var/www/html
   - /etc/localtime:/etc/localtime:ro
  environment:
   VIRTUAL_HOST: appform.local.lcl
  links:
   - mysql
#  entrypoint: /etc/servies.sh
  cap_add:
   - ALL
  privileged: true
  ports: 
   - '80:80'

